---
http_interactions:
- request:
    method: get
    uri: http://localhost:8080/hawkular/inventory/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Content-Type:
      - application/json
      Host:
      - localhost:8080
      Authorization:
      - Basic amRvZTpwYXNzd29yZA==
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '173'
      Date:
      - Mon, 13 Nov 2017 12:09:58 GMT
    body:
      encoding: UTF-8
      string: '{"Implementation-Version":"1.0.0.Final-SRC-revision-5402471e65caef238c019c107814982990179690","Built-From-Git-SHA1":"5402471e65caef238c019c107814982990179690","status":"UP"}'
    http_version: 
  recorded_at: Mon, 13 Nov 2017 12:09:58 GMT
- request:
    method: get
    uri: http://localhost:8080/hawkular/inventory/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Content-Type:
      - application/json
      Host:
      - localhost:8080
      Authorization:
      - Basic amRvZTpwYXNzd29yZA==
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '173'
      Date:
      - Mon, 13 Nov 2017 12:09:58 GMT
    body:
      encoding: UTF-8
      string: '{"Implementation-Version":"1.0.0.Final-SRC-revision-5402471e65caef238c019c107814982990179690","Built-From-Git-SHA1":"5402471e65caef238c019c107814982990179690","status":"UP"}'
    http_version: 
  recorded_at: Mon, 13 Nov 2017 12:09:58 GMT
recorded_with: VCR 3.0.3
