---
http_interactions:
- request:
    method: get
    uri: http://localhost:8081/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
      Host:
      - localhost:8081
      Authorization:
      - Basic amRvZTpwYXNzd29yZA==
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache
      Vary:
      - Origin,Accept-Encoding
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '150'
      Date:
      - Mon, 13 Nov 2017 12:09:58 GMT
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.28.2.Final","Built-From-Git-SHA1":"8d5399b7af220b9a8ab63457bce92ffa2df451b3","Cassandra":"up"}'
    http_version: 
  recorded_at: Mon, 13 Nov 2017 12:09:58 GMT
- request:
    method: post
    uri: http://localhost:8081/hawkular/metrics/availability/<%= id %>/raw
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= minus50 %>,"value":"up"},{"timestamp":<%= minus40 %>,"value":"up"},{"timestamp":<%= minus30 %>,"value":"down"},{"timestamp":<%= minus20 %>,"value":"down"},{"timestamp":<%= minus10 %>,"value":"down"},{"timestamp":<%= now %>,"value":"up"}]'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
      Content-Length:
      - '253'
      Host:
      - localhost:8081
      Authorization:
      - Basic amRvZTpwYXNzd29yZA==
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache
      Vary:
      - Origin,Accept-Encoding
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Length:
      - '0'
      Date:
      - Mon, 13 Nov 2017 12:09:58 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 13 Nov 2017 12:09:58 GMT
- request:
    method: get
    uri: http://localhost:8081/hawkular/metrics/availability/<%= id %>/raw/?distinct=true&order=ASC
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - <%= vcr_test_tenant %>
      Content-Type:
      - application/json
      Host:
      - localhost:8081
      Authorization:
      - Basic amRvZTpwYXNzd29yZA==
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache
      Vary:
      - Origin,Accept-Encoding
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '126'
      Date:
      - Mon, 13 Nov 2017 12:09:58 GMT
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= minus50 %>,"value":"up"},{"timestamp":<%= minus30 %>,"value":"down"},{"timestamp":<%= now %>,"value":"up"}]'
    http_version: 
  recorded_at: Mon, 13 Nov 2017 12:09:58 GMT
recorded_with: VCR 3.0.3
